feat: add ability to set default dialog open state
chakra-ui/zag pull request #114
Opened 2022-05-27 12:41 UTC by alexluong

Closes # 

## 📝 Description

Enable users to set whether dialog should open or close on default

## ⛳️ Current behavior (updates)

Currently, all dialog is closed on default.

## 🚀 New behavior

If user pass `defaultIsOpen: true` to context, the dialog will transition to `open` state after setup.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

---

I also added a new Next.js page and Playwright test to test this behaviour.

I'd love to hear your input on these:

- config name: `defaultIsOpen`, I take this from Chakra UI naming convention, feel free to suggest alternatives
- the machine code / guard usage; as the guard is fairly straightforward, I just wrote the guard inline instead of giving it a name
- The name of the new route: "Dialog Default Open" - "/dialog-default-open"
- The e2e test to check if the dialog is open. I just check if the close button is focused.

If everything looks good, I'll follow up with the pages for Vue and Svelte as well.

And lastly, as this is my first PR, I'd appreciate some help with the next step (changelog, publishing, etc), or feel free to take over!

2022-05-27 16:37 UTC, segunadebayo requested changes

2022-05-27 16:37 UTC, segunadebayo commented on packages/machines/dialog/src/dialog.types.ts
> +  defaultIsOpen?: boolean
Please use `isOpen` or `open` instead.

As much as we're trying to model things around Chakra UI. We try to keep Zag naming convention as close to DOM as possible.

2022-05-27 16:37 UTC, segunadebayo commented on packages/machines/dialog/src/dialog.machine.ts
> +            ],
I think we can simplify this

```suggestion
            SETUP:  {
                target: ctx.open ? "open": "closed",
                actions: "setupDocument",
              },
```

2022-05-27 16:38 UTC, segunadebayo commented
To generate a changeset for this PR, run `yarn changeset` and follow the prompts.

2022-05-28 04:19 UTC, alexluong commented
Thanks @segunadebayo for the feedbacks, made those changes + added example page for Solid and Vue + generated changeset

2022-05-28 16:35 UTC, anubra266 commented on packages/machines/dialog/src/dialog.types.ts
> +  isOpen?: boolean
I feel `defaultOpen` is better here since it's not controlled
```suggestion
  isOpen?: boolean
```

2022-05-28 16:41 UTC, alexluong commented on packages/machines/dialog/src/dialog.types.ts
> +  isOpen?: boolean
I agree that it's probably better to have "default" somewhere in it as `isOpen` can be misinterpreted as a controlled variable.

2022-05-28 16:45 UTC, segunadebayo commented on packages/machines/dialog/src/dialog.types.ts
> +  isOpen?: boolean
The notion of controller and uncontrolled is something we need to be cautious about as it’s a concept that’s generalized by React. 

I think we need to broaden our scope beyond React and see as if we’re building DOM primitives. Solid.js for example, doesn’t have the notion of controlled-uncontrolled since it compiles directly to the DOM (no VDOM)

Native APIs use naming like value, open, checked, etc to denote the initial state of the element. I recommend we stick with this approach.

2022-05-30 16:07 UTC, alexluong commented on packages/machines/dialog/src/dialog.types.ts
> +  isOpen?: boolean
Makes sense, thanks for the explanation.

Anything else I can do to move the PR forward?

2022-06-04 09:15 UTC, merged